server:
  port: 8123

spring:
  datasource:
    url: jdbc:mysql://todaysgym.ceoflgvhioeh.ap-northeast-2.rds.amazonaws.com:3306/todaysgym_db?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username: root
    password: todaysgym123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl : true
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

cloud:
  aws:
    credentials:
      accessKey: AKIAWZAG77WW5CBCEQAD
      secretKey: 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
    s3:
      bucket: todaysgym-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false






  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 429955294987-388f8t5sfg593faspeftn44nkrthu8mc.apps.googleusercontent.com
            client-secret: MUSODP-tzCziqenf3yR4UnPgcj3-xYHcO1J
            scope: profile, email



#구글 비밀번호
google:
  default:
    password: google123


#카카오 임시 비밀번호
kakao:
  default:
    password: kakao123
